<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Aidan Teeger">
<meta name="dcterms.date" content="2026-05-17">

<title>blog - Poisson Regression and Maximum Likelihood Estimation</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com" rel="" target=""><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Poisson Regression and Maximum Likelihood Estimation</h1>
            <p class="subtitle lead">A Case Study of Blueprinty’s Software and Patent Awards</p>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Aidan Teeger </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">May 17, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Blueprinty is a small firm that sells software to engineering firms preparing patent applications for the US Patent and Trademark Office. Their marketing team would like to claim that customers using the software are more successful at getting patents granted than firms that do not. The cleanest test of that claim would be a within-firm comparison, measuring each firm’s patent counts before and after adopting the software. No such data exists.</p>
<p>What Blueprinty does have is a cross-section of 1,500 mature engineering firms observed over a five-year window. For each firm we observe the number of patents awarded, the firm’s age, the region of the country it operates in, and whether or not it uses Blueprinty’s software. With only this snapshot, a raw comparison of average patent counts between customers and non-customers is not enough to settle the question. Customers are self-selected, so any unadjusted gap could simply reflect that the kinds of firms that buy the software are different in ways that also drive patent success. Older firms, firms in patent-heavy regions, or firms with deeper R&amp;D pipelines might both be more likely to subscribe and more likely to file successful applications. The job of this post is to account for those background differences using a Poisson regression model fitted via maximum likelihood estimation, and isolate what we can plausibly attribute to the software itself.</p>
</section>
<section id="exploring-the-data" class="level2">
<h2 class="anchored" data-anchor-id="exploring-the-data">Exploring the Data</h2>
<p>We start by loading the data and looking at how patent counts, regions, and firm ages compare between customers and non-customers.</p>
<div class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> optimize</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.special <span class="im">import</span> gammaln</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"blueprinty.csv"</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="setup" class="cell-output cell-output-display" data-execution_count="1">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">patents</th>
<th data-quarto-table-cell-role="th">region</th>
<th data-quarto-table-cell-role="th">age</th>
<th data-quarto-table-cell-role="th">iscustomer</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0</td>
<td>Midwest</td>
<td>32.5</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>3</td>
<td>Southwest</td>
<td>37.5</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>4</td>
<td>Northwest</td>
<td>27.0</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>3</td>
<td>Northeast</td>
<td>24.5</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>3</td>
<td>Southwest</td>
<td>37.0</td>
<td>0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The figure below puts the distribution of patent counts for customers and non-customers side by side. Sharing the x-axis makes the comparison clean.</p>
<div class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div id="fig-patents" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/fig-patents-output-1.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1: Distribution of patents awarded over the last 5 years, split by Blueprinty customer status.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-execution_count="3">
<div id="patent-means" class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">n</th>
<th data-quarto-table-cell-role="th">mean</th>
<th data-quarto-table-cell-role="th">median</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Status</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Non-customer</td>
<td>1019</td>
<td>3.473</td>
<td>3.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Customer</td>
<td>481</td>
<td>4.133</td>
<td>4.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The shapes of the two distributions look broadly similar, but the customer distribution is shifted noticeably to the right. Customers average about 4.13 patents over the five-year window compared with 3.47 for non-customers, a raw gap of roughly 0.66 patents per firm. Taken at face value this looks like evidence in favour of the marketing claim, but it is exactly the comparison the introduction warned against. We need to check whether customers and non-customers look the same on other dimensions before treating this gap as causal.</p>
<p>The next two figures compare the distribution of regions and the distribution of firm age across the two groups.</p>
<div class="cell" data-execution_count="4">
<div id="region-dist" class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Non-customers (%)</th>
<th data-quarto-table-cell-role="th">Customers (%)</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Region</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Midwest</td>
<td>18.4</td>
<td>7.7</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Northeast</td>
<td>26.8</td>
<td>68.2</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Northwest</td>
<td>15.5</td>
<td>6.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">South</td>
<td>15.3</td>
<td>7.3</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Southwest</td>
<td>24.0</td>
<td>10.8</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The regional pattern is striking. Customers are heavily concentrated in the Northeast, with about 68% of all customers located there compared with only 27% of non-customers. Every other region is sharply under-represented among customers. This is the most important confounder to keep in mind going forward. If the Northeast happens to be a high-patenting region for reasons unrelated to Blueprinty, that geographic concentration alone will inflate the raw customer mean.</p>
<div class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div id="fig-age" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/fig-age-output-1.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;2: Distribution of firm age (years since incorporation) by customer status.</figcaption>
</figure>
</div>
</div>
</div>
<p>Age looks broadly similar across the two groups. Customers are slightly older on average (about 26.9 years versus 26.1) and the customer distribution has a touch more dispersion, but the difference is small relative to the regional imbalance. Age is still worth controlling for because patent productivity is unlikely to be flat across the life of a firm. Mature firms tend to have more accumulated R&amp;D capacity than very young firms, but very old firms can plateau or wind down. Anything resembling a hump-shaped relationship needs at least a quadratic term in age to be captured properly.</p>
<p>The takeaway from the exploration is that customers and non-customers do not look alike. A simple comparison of means will conflate Blueprinty’s effect with the regional and (to a smaller extent) age differences between the groups. We need a model that lets us hold those characteristics fixed.</p>
</section>
<section id="a-simple-poisson-model-via-maximum-likelihood" class="level2">
<h2 class="anchored" data-anchor-id="a-simple-poisson-model-via-maximum-likelihood">A Simple Poisson Model via Maximum Likelihood</h2>
<p>Patent counts are non-negative integers. Modelling them with a Normal distribution would put probability mass on negative and non-integer outcomes, neither of which is meaningful for a count of patents. The Poisson distribution is the natural starting point. It assigns probability only to non-negative integers and is governed by a single rate parameter <span class="math inline">\(\lambda\)</span>, which equals both the mean and the variance of the distribution.</p>
<section id="deriving-the-likelihood" class="level3">
<h3 class="anchored" data-anchor-id="deriving-the-likelihood">Deriving the likelihood</h3>
<p>Assume each firm’s patent count <span class="math inline">\(Y_i\)</span> is an independent draw from the same Poisson distribution with rate <span class="math inline">\(\lambda\)</span>. The probability mass function is</p>
<p><span class="math display">\[
f(Y_i \mid \lambda) = \frac{e^{-\lambda}\lambda^{Y_i}}{Y_i!}.
\]</span></p>
<p>Because the <span class="math inline">\(Y_i\)</span> are iid, the joint likelihood across all <span class="math inline">\(n\)</span> firms is the product of the individual densities,</p>
<p><span class="math display">\[
L(\lambda \mid Y_1, \ldots, Y_n) = \prod_{i=1}^{n} \frac{e^{-\lambda}\lambda^{Y_i}}{Y_i!}.
\]</span></p>
<p>Taking logs turns the product into a sum and makes the function much easier to work with,</p>
<p><span class="math display">\[
\ell(\lambda) = \sum_{i=1}^{n} \left[ -\lambda + Y_i \log \lambda - \log(Y_i!) \right]
\;=\; -n\lambda + \log(\lambda)\sum_{i=1}^{n} Y_i - \sum_{i=1}^{n} \log(Y_i!).
\]</span></p>
<p>The last term does not involve <span class="math inline">\(\lambda\)</span>, so it does not affect where the maximum is. Differentiating with respect to <span class="math inline">\(\lambda\)</span> and setting the derivative to zero gives a clean closed-form answer,</p>
<p><span class="math display">\[
\frac{d\ell}{d\lambda} = -n + \frac{1}{\lambda}\sum_{i=1}^{n} Y_i = 0
\quad\Longrightarrow\quad
\hat\lambda_{\text{MLE}} = \bar{Y}.
\]</span></p>
<p>That result is reassuring. The mean of a Poisson distribution is <span class="math inline">\(\lambda\)</span>, and the MLE turns out to be the sample analogue.</p>
</section>
<section id="coding-and-plotting-the-log-likelihood" class="level3">
<h3 class="anchored" data-anchor-id="coding-and-plotting-the-log-likelihood">Coding and plotting the log-likelihood</h3>
<div id="poisson-loglik" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> poisson_loglikelihood(lam, Y):</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> lam <span class="op">&lt;=</span> <span class="dv">0</span>:</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="op">-</span>np.inf</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span><span class="bu">len</span>(Y) <span class="op">*</span> lam <span class="op">+</span> np.log(lam) <span class="op">*</span> Y.<span class="bu">sum</span>() <span class="op">-</span> gammaln(Y <span class="op">+</span> <span class="dv">1</span>).<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We use <code>gammaln(Y + 1)</code> instead of <code>log(Y!)</code> because <code>gammaln</code> is numerically stable for any non-negative integer <span class="math inline">\(Y\)</span>. The two are equivalent since <span class="math inline">\(\log(Y!) = \log\Gamma(Y+1)\)</span>.</p>
<p>Plotting the log-likelihood as a function of <span class="math inline">\(\lambda\)</span> over a sensible range gives a quick visual sanity check on where the maximum sits.</p>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>Y <span class="op">=</span> df[<span class="st">"patents"</span>].values.astype(<span class="bu">float</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>lam_grid <span class="op">=</span> np.linspace(<span class="fl">0.5</span>, <span class="dv">8</span>, <span class="dv">300</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>loglik_vals <span class="op">=</span> [poisson_loglikelihood(l, Y) <span class="cf">for</span> l <span class="kw">in</span> lam_grid]</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="fl">4.5</span>))</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>ax.plot(lam_grid, loglik_vals, color<span class="op">=</span><span class="st">"steelblue"</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>ax.axvline(Y.mean(), color<span class="op">=</span><span class="st">"darkorange"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>           label<span class="op">=</span><span class="vs">fr"$\bar Y = </span><span class="sc">{</span>Y<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="vs">$"</span>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="vs">r"$\lambda$"</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Log-likelihood"</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>ax.legend()</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>ax.spines[[<span class="st">"top"</span>, <span class="st">"right"</span>]].set_visible(<span class="va">False</span>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-loglik" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/fig-loglik-output-1.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;3: Log-likelihood of the simple Poisson model as a function of <span class="math inline">\(\lambda\)</span>, evaluated on the observed patent counts. The dashed line marks the sample mean.</figcaption>
</figure>
</div>
</div>
</div>
<p>The curve is smooth and concave, with a single peak. Reading the MLE off the plot is just a matter of finding the value of <span class="math inline">\(\lambda\)</span> at which the curve is highest. That point sits right at the sample mean of the data (about 3.68), exactly as the derivation said it should.</p>
</section>
<section id="finding-the-mle-numerically" class="level3">
<h3 class="anchored" data-anchor-id="finding-the-mle-numerically">Finding the MLE numerically</h3>
<p>A closed-form solution is a luxury we won’t have once we extend the model to a regression. It’s worth confirming we can also recover the MLE by handing the log-likelihood to an optimizer.</p>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>neg_loglik <span class="op">=</span> <span class="kw">lambda</span> lam: <span class="op">-</span>poisson_loglikelihood(lam[<span class="dv">0</span>], Y)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>res_simple <span class="op">=</span> optimize.minimize(neg_loglik, x0<span class="op">=</span>[<span class="fl">1.0</span>], method<span class="op">=</span><span class="st">"Nelder-Mead"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>pd.DataFrame({</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Method"</span>: [<span class="st">"Analytical MLE (sample mean)"</span>, <span class="st">"Numerical MLE (Nelder-Mead)"</span>],</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Estimate of lambda"</span>: [Y.mean(), res_simple.x[<span class="dv">0</span>]],</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>}).<span class="bu">round</span>(<span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="poisson-mle-numeric" class="cell-output cell-output-display" data-execution_count="8">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Method</th>
<th data-quarto-table-cell-role="th">Estimate of lambda</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Analytical MLE (sample mean)</td>
<td>3.684667</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Numerical MLE (Nelder-Mead)</td>
<td>3.684668</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The two estimates agree to six decimal places. They have to. The analytical derivation showed that <span class="math inline">\(\bar Y\)</span> is the unique maximum of the log-likelihood for the simple Poisson model. The optimizer just finds the same answer through numerical search instead of calculus. Any tiny discrepancy is purely a function of the optimizer’s stopping tolerance.</p>
</section>
</section>
<section id="poisson-regression" class="level2">
<h2 class="anchored" data-anchor-id="poisson-regression">Poisson Regression</h2>
<p>The simple Poisson model assumes that every firm has the same patent rate <span class="math inline">\(\lambda\)</span>. That clearly does not fit our data. The exploration showed that customers, regions, and age groups produce different averages. The fix is to let <span class="math inline">\(\lambda\)</span> depend on the firm’s characteristics through a regression structure,</p>
<p><span class="math display">\[
Y_i \sim \text{Poisson}(\lambda_i), \qquad \lambda_i = \exp(X_i'\beta).
\]</span></p>
<p>The exponential link is doing real work here. The linear predictor <span class="math inline">\(X_i'\beta\)</span> can take any value on the real line depending on the covariates and coefficients, but <span class="math inline">\(\lambda_i\)</span> must be strictly positive to be a valid Poisson rate. Wrapping the linear predictor in <span class="math inline">\(\exp(\cdot)\)</span> guarantees that constraint is satisfied automatically without putting any restrictions on the values <span class="math inline">\(\beta\)</span> can take during estimation.</p>
<p>Plugging <span class="math inline">\(\lambda_i = \exp(X_i'\beta)\)</span> into the Poisson log-likelihood, the per-firm contribution becomes</p>
<p><span class="math display">\[
\ell_i(\beta) = Y_i \, X_i'\beta - \exp(X_i'\beta) - \log(Y_i!),
\]</span></p>
<p>and the full sample log-likelihood is just the sum over firms,</p>
<p><span class="math display">\[
\ell(\beta) = \sum_{i=1}^{n} \left[ Y_i \, X_i'\beta - \exp(X_i'\beta) - \log(Y_i!) \right].
\]</span></p>
<section id="coding-the-regression-log-likelihood" class="level3">
<h3 class="anchored" data-anchor-id="coding-the-regression-log-likelihood">Coding the regression log-likelihood</h3>
<div id="poisson-reg-loglik" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> poisson_regression_loglikelihood(beta, Y, X):</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    eta <span class="op">=</span> np.clip(X <span class="op">@</span> beta, <span class="op">-</span><span class="dv">30</span>, <span class="dv">30</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    lam <span class="op">=</span> np.exp(eta)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (Y <span class="op">*</span> eta <span class="op">-</span> lam <span class="op">-</span> gammaln(Y <span class="op">+</span> <span class="dv">1</span>)).<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code>np.clip</code> step is a defensive measure. During optimization the optimizer may briefly try parameter values that produce extreme linear predictors, and <code>exp</code> of a large number quickly overflows to infinity. Capping <span class="math inline">\(\eta\)</span> at a reasonable range avoids numerical blowups without changing the answer near the optimum, where the linear predictors are all moderate.</p>
</section>
<section id="building-the-design-matrix" class="level3">
<h3 class="anchored" data-anchor-id="building-the-design-matrix">Building the design matrix</h3>
<p>The design matrix <span class="math inline">\(X\)</span> has 1,500 rows (one per firm) and 8 columns. The first column is a constant equal to 1 (the intercept), then <code>age</code> and <code>age</code> squared, then four region dummies, then the binary <code>iscustomer</code> indicator.</p>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"age_sq"</span>] <span class="op">=</span> df[<span class="st">"age"</span>] <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>region_dummies <span class="op">=</span> pd.get_dummies(df[<span class="st">"region"</span>], prefix<span class="op">=</span><span class="st">"region"</span>, drop_first<span class="op">=</span><span class="va">True</span>).astype(<span class="bu">int</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>X_df <span class="op">=</span> pd.concat([</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    pd.Series(<span class="fl">1.0</span>, index<span class="op">=</span>df.index, name<span class="op">=</span><span class="st">"intercept"</span>),</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    df[[<span class="st">"age"</span>, <span class="st">"age_sq"</span>]],</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    region_dummies,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">"iscustomer"</span>].astype(<span class="bu">float</span>).rename(<span class="st">"iscustomer"</span>),</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> X_df.values.astype(<span class="bu">float</span>)</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a><span class="bu">list</span>(X_df.columns)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="build-x" class="cell-output cell-output-display" data-execution_count="10">
<pre><code>['intercept',
 'age',
 'age_sq',
 'region_Northeast',
 'region_Northwest',
 'region_South',
 'region_Southwest',
 'iscustomer']</code></pre>
</div>
</div>
<p>Two construction choices are worth flagging for the reader. First, we include both <code>age</code> and <code>age</code> squared. The reason was hinted at in the exploration. The relationship between firm age and patent productivity is not obviously linear. Very young firms have less accumulated capacity, very old firms can plateau, and the sweet spot may sit somewhere in the middle. Adding a quadratic term lets the model trace out a hump (or a bowl) instead of forcing a straight line.</p>
<p>Second, we drop one of the five region indicators. <code>pd.get_dummies(..., drop_first=True)</code> keeps four of the five regions, omitting <code>Midwest</code>. The omitted category is folded into the intercept and serves as the reference level. If we kept all five region dummies they would sum to the intercept column, creating perfect collinearity and making the design matrix singular. The interpretation does not change. Each region coefficient measures the log-rate of patenting relative to a Midwest firm with the same age and customer status.</p>
</section>
<section id="fitting-via-scipy.optimize.minimize" class="level3">
<h3 class="anchored" data-anchor-id="fitting-via-scipy.optimize.minimize">Fitting via <code>scipy.optimize.minimize</code></h3>
<p>We hand the negative log-likelihood to <code>scipy.optimize.minimize</code> and ask for an approximation of the inverse Hessian along the way. The standard errors of the MLE come from the diagonal of the inverse of the Hessian of the negative log-likelihood, which is exactly the asymptotic variance of the maximum likelihood estimator. Because the optimizer’s internal Hessian approximation can be loose, we re-compute the Hessian by central differences on the analytic gradient at the optimum and invert that for a tighter answer.</p>
<div id="fit-mle" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> neg_loglik_reg(beta):</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    eta <span class="op">=</span> np.clip(X <span class="op">@</span> beta, <span class="op">-</span><span class="dv">30</span>, <span class="dv">30</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    lam <span class="op">=</span> np.exp(eta)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>(Y <span class="op">*</span> eta <span class="op">-</span> lam <span class="op">-</span> gammaln(Y <span class="op">+</span> <span class="dv">1</span>)).<span class="bu">sum</span>()</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> grad_neg_loglik_reg(beta):</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    eta <span class="op">=</span> np.clip(X <span class="op">@</span> beta, <span class="op">-</span><span class="dv">30</span>, <span class="dv">30</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    lam <span class="op">=</span> np.exp(eta)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>(X.T <span class="op">@</span> (Y <span class="op">-</span> lam))</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>beta0 <span class="op">=</span> np.zeros(X.shape[<span class="dv">1</span>])</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>beta0[<span class="dv">0</span>] <span class="op">=</span> np.log(Y.mean())</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> optimize.minimize(</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>    neg_loglik_reg,</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>    x0<span class="op">=</span>beta0,</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>    method<span class="op">=</span><span class="st">"BFGS"</span>,</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>    jac<span class="op">=</span>grad_neg_loglik_reg,</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>    options<span class="op">=</span>{<span class="st">"gtol"</span>: <span class="fl">1e-10</span>, <span class="st">"maxiter"</span>: <span class="dv">1000</span>},</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>beta_hat <span class="op">=</span> result.x</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> numerical_hessian(grad_fn, x, h<span class="op">=</span><span class="fl">1e-5</span>):</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> <span class="bu">len</span>(x)</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>    H <span class="op">=</span> np.zeros((n, n))</span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(n):</span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a>        x_plus, x_minus <span class="op">=</span> x.copy(), x.copy()</span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a>        x_plus[i] <span class="op">+=</span> h</span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a>        x_minus[i] <span class="op">-=</span> h</span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a>        H[:, i] <span class="op">=</span> (grad_fn(x_plus) <span class="op">-</span> grad_fn(x_minus)) <span class="op">/</span> (<span class="dv">2</span> <span class="op">*</span> h)</span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (H <span class="op">+</span> H.T) <span class="op">/</span> <span class="dv">2</span></span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-34"><a href="#cb8-34" aria-hidden="true" tabindex="-1"></a>H_neg <span class="op">=</span> numerical_hessian(grad_neg_loglik_reg, beta_hat)</span>
<span id="cb8-35"><a href="#cb8-35" aria-hidden="true" tabindex="-1"></a>cov <span class="op">=</span> np.linalg.inv(H_neg)</span>
<span id="cb8-36"><a href="#cb8-36" aria-hidden="true" tabindex="-1"></a>se <span class="op">=</span> np.sqrt(np.diag(cov))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="comparing-the-hand-rolled-mle-to-statsmodels.glm" class="level3">
<h3 class="anchored" data-anchor-id="comparing-the-hand-rolled-mle-to-statsmodels.glm">Comparing the hand-rolled MLE to <code>statsmodels.GLM</code></h3>
<p>A standard sanity check is to fit the same model using a well-tested implementation and confirm the answers line up.</p>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>glm_fit <span class="op">=</span> sm.GLM(Y, X, family<span class="op">=</span>sm.families.Poisson()).fit()</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>results_table <span class="op">=</span> pd.DataFrame({</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Variable"</span>: X_df.columns,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"MLE (optim)"</span>: beta_hat,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"SE (optim)"</span>: se,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"GLM coef"</span>: glm_fit.params,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"GLM SE"</span>: glm_fit.bse,</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>}).<span class="bu">round</span>(<span class="dv">4</span>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>results_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="glm-check" class="cell-output cell-output-display" data-execution_count="12">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Variable</th>
<th data-quarto-table-cell-role="th">MLE (optim)</th>
<th data-quarto-table-cell-role="th">SE (optim)</th>
<th data-quarto-table-cell-role="th">GLM coef</th>
<th data-quarto-table-cell-role="th">GLM SE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>intercept</td>
<td>-0.5089</td>
<td>0.1832</td>
<td>-0.5089</td>
<td>0.1832</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>age</td>
<td>0.1486</td>
<td>0.0139</td>
<td>0.1486</td>
<td>0.0139</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>age_sq</td>
<td>-0.0030</td>
<td>0.0003</td>
<td>-0.0030</td>
<td>0.0003</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>region_Northeast</td>
<td>0.0292</td>
<td>0.0436</td>
<td>0.0292</td>
<td>0.0436</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>region_Northwest</td>
<td>-0.0176</td>
<td>0.0538</td>
<td>-0.0176</td>
<td>0.0538</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>region_South</td>
<td>0.0566</td>
<td>0.0527</td>
<td>0.0566</td>
<td>0.0527</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>region_Southwest</td>
<td>0.0506</td>
<td>0.0472</td>
<td>0.0506</td>
<td>0.0472</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>iscustomer</td>
<td>0.2076</td>
<td>0.0309</td>
<td>0.2076</td>
<td>0.0309</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The two sets of estimates agree to four decimal places on both the coefficients and the standard errors. Any residual difference would reflect the numerical precision of the Hessian approximation and is well within rounding. This confirms that the log-likelihood function and the optimization machinery are working correctly.</p>
</section>
<section id="interpreting-the-coefficients" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-the-coefficients">Interpreting the coefficients</h3>
<p>Poisson regression coefficients are interpreted on the log-rate scale, so a coefficient of <span class="math inline">\(\beta_k\)</span> means that a one-unit increase in <span class="math inline">\(X_k\)</span> multiplies the expected patent count by <span class="math inline">\(\exp(\beta_k)\)</span>, holding the other covariates fixed.</p>
<p>The <code>age</code> and <code>age_sq</code> coefficients have opposite signs (positive on <code>age</code>, negative on <code>age_sq</code>), which produces the hump shape we anticipated. Patent productivity rises with firm age up to a point and then tapers off as firms mature.</p>
<p>The region coefficients are all small and most are statistically indistinguishable from zero relative to the Midwest reference category. Whatever regional differences exist are modest once age and customer status are controlled for.</p>
<p>The coefficient that the marketing team cares about is <code>iscustomer</code>. The estimate is 0.21 with a standard error of 0.031. That is roughly 6.7 standard errors away from zero, so the effect is precisely estimated and unlikely to be a fluke of sampling. On the rate scale, <span class="math inline">\(\exp(0.21) \approx 1.23\)</span>. Holding age and region fixed, Blueprinty’s customers are expected to produce about 23% more patents over a five-year window than otherwise comparable non-customers. The sign and magnitude both seem sensible. The effect is large enough to matter commercially but not so enormous that it strains credulity.</p>
</section>
</section>
<section id="the-effect-of-blueprintys-software" class="level2">
<h2 class="anchored" data-anchor-id="the-effect-of-blueprintys-software">The Effect of Blueprinty’s Software</h2>
<p>The 23% figure from the previous section is a relative effect on the rate. It is informative, but a marketing-facing answer often wants an absolute number. How many more patents does Blueprinty’s software add to a typical firm’s five-year haul? Because the model is multiplicative in <span class="math inline">\(\lambda\)</span> rather than additive, the coefficient on <code>iscustomer</code> does not translate directly into “extra patents.” We need to do the translation through a counterfactual exercise.</p>
<p>The idea is straightforward. Take the fitted model, then for every firm in the sample compute two predictions: one assuming the firm is not a Blueprinty customer, and one assuming it is. Everything else (age, age squared, region) stays at the firm’s actual observed values. The difference between the two predictions, averaged across firms, is the model-implied average effect of subscribing.</p>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>cust_idx <span class="op">=</span> <span class="bu">list</span>(X_df.columns).index(<span class="st">"iscustomer"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>X_0 <span class="op">=</span> X.copy()</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>X_0[:, cust_idx] <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>X_1 <span class="op">=</span> X.copy()</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>X_1[:, cust_idx] <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>y_hat_0 <span class="op">=</span> np.exp(X_0 <span class="op">@</span> beta_hat)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>y_hat_1 <span class="op">=</span> np.exp(X_1 <span class="op">@</span> beta_hat)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>ate <span class="op">=</span> (y_hat_1 <span class="op">-</span> y_hat_0).mean()</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>pd.DataFrame({</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Quantity"</span>: [</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Mean predicted patents if no firm were a customer"</span>,</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Mean predicted patents if every firm were a customer"</span>,</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Average effect of being a customer (patents per firm)"</span>,</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Relative uplift"</span>,</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Value"</span>: [</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>y_hat_0<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="ss">"</span>,</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>y_hat_1<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="ss">"</span>,</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>ate<span class="sc">:.3f}</span><span class="ss">"</span>,</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>(y_hat_1.mean() <span class="op">/</span> y_hat_0.mean() <span class="op">-</span> <span class="dv">1</span>) <span class="op">*</span> <span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">%"</span>,</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="counterfactual" class="cell-output cell-output-display" data-execution_count="13">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Quantity</th>
<th data-quarto-table-cell-role="th">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Mean predicted patents if no firm were a customer</td>
<td>3.436</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Mean predicted patents if every firm were a cu...</td>
<td>4.229</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Average effect of being a customer (patents pe...</td>
<td>0.793</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Relative uplift</td>
<td>23.1%</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Averaged across all 1,500 firms in the sample, switching the customer flag from 0 to 1 raises predicted patents over the five-year window from about 3.44 to about 4.23. That is an average lift of roughly 0.79 patents per firm, equivalent to the 23% relative uplift we read off the coefficient earlier.</p>
<section id="what-this-analysis-does-and-does-not-show" class="level3">
<h3 class="anchored" data-anchor-id="what-this-analysis-does-and-does-not-show">What this analysis does and does not show</h3>
<p>It is worth being precise about what this number means. The Poisson regression accounts for differences in firm age and regional location between customers and non-customers, both of which the exploration showed were nontrivial. After holding those characteristics fixed, customers still come out with a noticeably higher expected patent rate. That is genuine evidence in favour of Blueprinty’s marketing claim and the size of the effect (an extra 0.79 patents per firm on a base of 3.44) is commercially meaningful.</p>
<p>What the analysis does not establish is causation in the strict sense. This is an observational study, not a randomized experiment. Firms chose whether to subscribe to Blueprinty, and that choice may correlate with characteristics we do not observe. Firms with stronger in-house IP teams, more aggressive patent strategies, or deeper R&amp;D budgets might both be more likely to buy specialised software and more likely to file successful patents. None of those traits are in the data, so the model cannot adjust for them. The 23% uplift should therefore be read as “the gap in expected patent counts between customers and otherwise similar non-customers in this sample,” not as “the gap that would be produced by randomly assigning the software.” The only way to settle the causal question cleanly would be a randomized trial in which a subset of firms were offered Blueprinty’s software and the rest were not, with neither group differing systematically beforehand.</p>
<p>With that caveat noted, the evidence here is consistent with Blueprinty’s marketing claim and rules out the most obvious confounders. That is a reasonable place to stop for a first cut.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>